import { createHash,createHmac,randomBytes,randomUUID,scryptSync,timingSafeEqual } from "node:crypto";
import { prisma,getTenantId } from "@/lib/db";
import { getSchnellPushConfig,normalizeSchnellPushSubscription,sendEmptySchnellPush } from "@/lib/server/schnell-push";
export const CHEF_COOKIE="bb_chef_sess",CHEF_PUSH_SCOPE="chef_app";
const K={user:id=>`chef:user:${id}`,item:id=>`chef:item:${id}`,need:id=>`chef:need:${id}`,report:id=>`chef:report:${id}`,order:id=>`chef:order:${id}`,plan:id=>`chef:plan:${id}`,activity:id=>`chef:activity:${id}`,notification:id=>`chef:notification:${id}`};
const BOOTSTRAP_PIN_HASH="b23242eb0b393991c4d8f144b4ef05b2:5da976887f8982d2911a862c8221c7a4dff5f837e7b5d85369e41381d9c51cf1";
const rawSeeds=[
["Burger Fleisch","Fleisch & Chicken","QUANTITY","Kiste",2,null],["Crispy Chicken","Fleisch & Chicken","QUANTITY","Karton",2,null],["Chicken Finger","Fleisch & Chicken","QUANTITY","Karton",2,null],["Chicken Wings","Fleisch & Chicken","QUANTITY","Karton",2,null],
["Burger Brot","Brot","QUANTITY","Kiste",2,null],["Smash Brot","Brot","QUANTITY","Kiste",2,null],["Hotdog Brot","Brot","QUANTITY","Kiste",1,null],["Curly Fries","Tiefkühl","QUANTITY","Karton",3,null],["Pommes","Tiefkühl","QUANTITY","Karton",3,null],["Country Potatoes","Tiefkühl","QUANTITY","Karton",2,null],
["Halloumi","Käse & Special","STATUS","Packung",null,null],["Mozzarella","Käse & Special","STATUS","Packung",null,null],["Gorgonzola","Käse & Special","STATUS","Packung",null,null],["Cheddar","Käse & Special","STATUS","Packung",null,null],
["Iceberg Salat","Gemüse","STATUS","",null,null],["Tomaten","Gemüse","STATUS","",null,null],["Zwiebeln","Gemüse","STATUS","",null,null],["Spinat","Gemüse","STATUS","",null,null],["Avocado","Gemüse","STATUS","",null,null],["Guacamole","Gemüse","STATUS","",null,null],["Jalapeños","Gemüse","STATUS","",null,null],["Pickles","Gemüse","STATUS","",null,null],
["Ketchup","Saucen","STATUS","Karton",null,1],["Mayonnaise","Saucen","STATUS","Karton",null,1],["BB Sauce","Saucen","STATUS","",null,null],["Schwarze Sauce","Saucen","STATUS","",null,null],["Special Sauce","Saucen","STATUS","",null,null],
["BB Burger Box","Verpackung","STATUS","",null,null],["Kinder Box","Verpackung","STATUS","",null,null],["Menü Box","Verpackung","STATUS","",null,null],["Pommes Box","Verpackung","STATUS","",null,null],["Sauce Becher","Verpackung","STATUS","",null,null],["Sauce Becher Deckel","Verpackung","STATUS","",null,null],["Papiertüten","Verpackung","STATUS","",null,null],
["Servietten","Verbrauch","STATUS","",null,null],["Trinkhalme","Verbrauch","STATUS","",null,null],["Toilettenpapier","Verbrauch","STATUS","",null,null],["Einweghandschuhe","Verbrauch","STATUS","",null,null]];
const seeds=rawSeeds.map((r,i)=>({name:r[0],category:r[1],mode:r[2],unit:r[3],minStock:r[4],defaultOrderQty:r[5],supplierName:"",supplierWhatsapp:"",active:true,sortOrder:(i+1)*10}));
const now=()=>new Date().toISOString(),clean=(v,max=180)=>String(v??"").replace(/[\u0000-\u001f]/g," ").trim().slice(0,max),num=v=>v===""||v==null?null:(Number.isFinite(Number(v))&&Number(v)>=0?Number(v):null);
async function list(prefix,take=500){const tenantId=await getTenantId(),rows=await prisma.setting.findMany({where:{tenantId,key:{startsWith:prefix}},orderBy:{updatedAt:"desc"},take,select:{value:true}});return rows.map(r=>r.value)}
async function get(key){const tenantId=await getTenantId(),row=await prisma.setting.findUnique({where:{tenantId_key:{tenantId,key}},select:{value:true}});return row?.value||null}
async function put(key,value){const tenantId=await getTenantId();return prisma.setting.upsert({where:{tenantId_key:{tenantId,key}},update:{value},create:{tenantId,key,value}})}
async function del(key){const tenantId=await getTenantId();await prisma.setting.deleteMany({where:{tenantId,key}})}
const safeUser=u=>{const {pinHash,...safe}=u;return safe};
export function hashChefPin(pin){const salt=randomBytes(16),digest=scryptSync(pin,salt,32,{N:16384,r:8,p:1});return `${salt.toString("hex")}:${digest.toString("hex")}`}
export function verifyChefPin(pin,stored){try{const [s,d]=String(stored||"").split(":"),a=scryptSync(pin,Buffer.from(s,"hex"),32,{N:16384,r:8,p:1}),e=Buffer.from(d,"hex");return a.length===e.length&&timingSafeEqual(a,e)}catch{return false}}
function secret(){const s=clean(process.env.SESSION_SECRET||process.env.AUTH_SECRET,500);if(s.length<32)throw new Error("SESSION_SECRET_MISSING_OR_TOO_SHORT");return s}
export function createChefSession(sub){const p=Buffer.from(JSON.stringify({sub,exp:Math.floor(Date.now()/1000)+30*86400,v:1})).toString("base64url"),sig=createHmac("sha256",secret()).update(p).digest("base64url");return `chef:${p}.${sig}`}
function readSession(token){try{const raw=String(token||"");if(!raw.startsWith("chef:"))return null;const [p,s,...rest]=raw.slice(5).split(".");if(!p||!s||rest.length)return null;const e=createHmac("sha256",secret()).update(p).digest(),a=Buffer.from(s,"base64url");if(a.length!==e.length||!timingSafeEqual(a,e))return null;const x=JSON.parse(Buffer.from(p,"base64url").toString());return x?.v===1&&x?.sub&&Number(x.exp)>Date.now()/1000?x:null}catch{return null}}
function cookie(req,name){for(const part of (req.headers.get("cookie")||"").split(";")){const [k,...r]=part.trim().split("=");if(k===name)try{return decodeURIComponent(r.join("="))}catch{return r.join("=")}}return ""}
export async function ensureChefBootstrap(){if((await list("chef:user:",5)).length)return;const t=now();await put(K.user("bbchef-omer"),{id:"bbchef-omer",username:"omer",displayName:"Ömer",role:"ADMIN",canOrder:true,active:true,pinHash:BOOTSTRAP_PIN_HASH,createdAt:t,updatedAt:t});for(let i=0;i<seeds.length;i++){const id=`seed-${String(i+1).padStart(3,"0")}`;await put(K.item(id),{...seeds[i],id,createdAt:t,updatedAt:t})}}
export async function findChefUserByUsername(username){const q=clean(username,60).toLocaleLowerCase("de-DE");return (await list("chef:user:",100)).find(u=>String(u.username).toLocaleLowerCase("de-DE")===q)||null}
export async function requireChef(req){const s=readSession(cookie(req,CHEF_COOKIE));if(!s?.sub)return null;const u=await get(K.user(clean(s.sub,120)));return u?.active?u:null}
async function activity(u,action,detail){const x={id:randomUUID(),actorId:u.id,actorName:u.displayName,action,detail:clean(detail,500),createdAt:now()};await put(K.activity(x.id),x)}
export async function getChefState(me){await ensureChefBootstrap();const [items,needs,plans,reports,acts,users]=await Promise.all([list("chef:item:"),list("chef:need:"),list("chef:plan:",250),list("chef:report:",30),list("chef:activity:",50),me.role==="ADMIN"?list("chef:user:",100):Promise.resolve([])]),pc=getSchnellPushConfig();return{me:safeUser(me),items:items.filter(i=>i.active).sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name)),needs:needs.filter(n=>n.state==="OPEN"||n.state==="ORDERED").sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),plans:plans.filter(p=>p.active).sort((a,b)=>a.scheduledDate.localeCompare(b.scheduledDate)),reports:reports.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,10),activity:acts.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,30),users:users.map(safeUser),push:{configured:pc.configured,publicKey:pc.configured?pc.publicKey:""}}}
export async function saveChefReport(user,input){const entries=Array.isArray(input?.entries)?input.entries.slice(0,250):[],reportId=randomUUID(),createdAt=now();await put(K.report(reportId),{id:reportId,createdById:user.id,createdByName:user.displayName,voiceTranscript:clean(input?.voiceTranscript,4000),createdAt,entryCount:entries.length});const known=await list("chef:need:",500);let fresh=0;for(const raw of entries){const itemId=clean(raw?.itemId,120),item=itemId?await get(K.item(itemId)):null;if(!item?.active)continue;const currentQty=num(raw.currentQty);let neededQty=num(raw.neededQty);const s=clean(raw.status,20).toUpperCase(),status=["LOW","CRITICAL","OUT"].includes(s)?s:null;if(neededQty==null&&status&&item.defaultOrderQty!=null)neededQty=item.defaultOrderQty;const needsOrder=(neededQty!=null&&neededQty>0)||!!status;if(needsOrder){const old=known.find(n=>n.itemId===itemId&&n.state==="OPEN"),next=old?{...old,reportId,currentQty,neededQty,status,note:clean(raw.note,400),createdById:user.id,createdByName:user.displayName,createdAt}:{id:randomUUID(),itemId,reportId,currentQty,neededQty,status,note:clean(raw.note,400),state:"OPEN",createdById:user.id,createdByName:user.displayName,createdAt};await put(K.need(next.id),next);if(old)Object.assign(old,next);else{known.push(next);fresh++}}else if(raw.checked===true){for(const old of known.filter(n=>n.itemId===itemId&&n.state==="OPEN")){const next={...old,state:"RESOLVED"};await put(K.need(old.id),next);Object.assign(old,next)}}}await activity(user,"REPORT_SAVED",`${entries.length} ürün kontrol edildi${fresh?`, ${fresh} yeni eksik`:""}`);await createChefNotification({title:"BB Chef · Stok kontrolü",body:`${user.displayName} kontrolü kaydetti. ${entries.length} ürün güncellendi.`,url:"/chef"});return{reportId}}
function orderMessage(needs,items){const m=new Map(items.map(i=>[i.id,i]));return `Hallo, wir benötigen bitte:\n\n${needs.map(n=>{const i=m.get(n.itemId);if(!i)return"";const q=n.neededQty!=null?`${n.neededQty}${i.unit?` ${i.unit}`:""}`:i.defaultOrderQty!=null?`${i.defaultOrderQty}${i.unit?` ${i.unit}`:""}`:"bestellen";return `• ${i.name}: ${q}`}).filter(Boolean).join("\n")}\n\nVielen Dank!`}
export async function placeChefOrder(user,idsInput){if(!user.canOrder&&user.role!=="ADMIN")throw new Error("ORDER_PERMISSION_REQUIRED");const ids=Array.isArray(idsInput)?idsInput.map(x=>clean(x,120)).filter(Boolean).slice(0,100):[];if(!ids.length)throw new Error("NO_ORDER_ITEMS");const [all,items]=await Promise.all([list("chef:need:",500),list("chef:item:",500)]),selected=all.filter(n=>ids.includes(n.id)&&n.state==="OPEN");if(!selected.length)throw new Error("NO_OPEN_ORDER_ITEMS");const map=new Map(items.map(i=>[i.id,i])),names=new Set(selected.map(n=>map.get(n.itemId)?.supplierName||"").filter(Boolean));if(names.size>1)throw new Error("MULTIPLE_SUPPLIERS");const supplierName=String([...names][0]||"Lieferant"),supplierWhatsapp=selected.map(n=>map.get(n.itemId)?.supplierWhatsapp||"").find(Boolean)||"",message=orderMessage(selected,items),orderedAt=now();for(const n of selected)await put(K.need(n.id),{...n,state:"ORDERED",orderedById:user.id,orderedByName:user.displayName,orderedAt});const id=randomUUID();await put(K.order(id),{id,supplierName,supplierWhatsapp,needIds:selected.map(n=>n.id),message,orderedById:user.id,orderedByName:user.displayName,orderedAt});await activity(user,"ORDER_PLACED",`${supplierName}: ${selected.length} kalem`);await createChefNotification({title:"BB Chef · Sipariş verildi",body:`${user.displayName}, ${supplierName} için ${selected.length} kalemi siparişe gönderdi.`,url:"/chef"});const digits=String(supplierWhatsapp).replace(/\D/g,"");return{orderId:id,message,whatsappUrl:`https://wa.me/${digits}?text=${encodeURIComponent(message)}`}}
export async function receiveChefNeeds(user,idsInput){const ids=Array.isArray(idsInput)?idsInput.map(x=>clean(x,120)):[],needs=await list("chef:need:",500),t=now();let count=0;for(const n of needs.filter(n=>ids.includes(n.id)&&n.state==="ORDERED")){await put(K.need(n.id),{...n,state:"RECEIVED",receivedById:user.id,receivedByName:user.displayName,receivedAt:t});count++}if(count)await activity(user,"ORDER_RECEIVED",`${count} kalem geldi`);return{count}}
export async function upsertChefItem(user,input){if(user.role!=="ADMIN")throw new Error("ADMIN_REQUIRED");const id=clean(input?.id,120)||randomUUID(),old=await get(K.item(id)),t=now(),name=clean(input?.name,120);if(!name)throw new Error("ITEM_NAME_REQUIRED");const item={id,name,category:clean(input.category,100)||"Diğer",mode:clean(input.mode,20).toUpperCase()==="STATUS"?"STATUS":"QUANTITY",unit:clean(input.unit,40),minStock:num(input.minStock),defaultOrderQty:num(input.defaultOrderQty),supplierName:clean(input.supplierName,120),supplierWhatsapp:clean(input.supplierWhatsapp,50),active:input.active!==false,sortOrder:Number.isFinite(Number(input.sortOrder))?Number(input.sortOrder):old?.sortOrder||Date.now(),createdAt:old?.createdAt||t,updatedAt:t};await put(K.item(id),item);await activity(user,old?"ITEM_UPDATED":"ITEM_CREATED",item.name);return item}
export async function deleteChefItem(user,idInput){if(user.role!=="ADMIN")throw new Error("ADMIN_REQUIRED");const id=clean(idInput,120),old=await get(K.item(id));if(old){await put(K.item(id),{...old,active:false,updatedAt:now()});await activity(user,"ITEM_DISABLED",old.name)}return{ok:true}}
export async function upsertChefUser(actor,input){if(actor.role!=="ADMIN")throw new Error("ADMIN_REQUIRED");const id=clean(input?.id,120)||randomUUID(),old=await get(K.user(id)),username=clean(input.username,60).toLocaleLowerCase("de-DE"),displayName=clean(input.displayName,100),pin=clean(input.pin,40);if(!username||!displayName)throw new Error("USER_FIELDS_REQUIRED");if((await list("chef:user:",100)).some(u=>u.id!==id&&String(u.username).toLocaleLowerCase("de-DE")===username))throw new Error("USERNAME_EXISTS");if(!old&&pin.length<4)throw new Error("PIN_TOO_SHORT");const t=now(),u={id,username,displayName,role:clean(input.role,20).toUpperCase()==="ADMIN"?"ADMIN":"CHEF",canOrder:input.canOrder===true,active:input.active!==false,pinHash:pin?hashChefPin(pin):old?.pinHash||"",createdAt:old?.createdAt||t,updatedAt:t};await put(K.user(id),u);await activity(actor,old?"USER_UPDATED":"USER_CREATED",displayName);return safeUser(u)}
export async function upsertChefPlan(user,input){const id=clean(input?.id,120)||randomUUID(),old=await get(K.plan(id)),t=now(),title=clean(input.title,140),scheduledDate=clean(input.scheduledDate,20);if(!title||!/^\d{4}-\d{2}-\d{2}$/.test(scheduledDate))throw new Error("PLAN_FIELDS_REQUIRED");const p={id,title,note:clean(input.note,500),scheduledDate,remindDayBefore:input.remindDayBefore!==false,remindSameDay:input.remindSameDay!==false,recurrence:clean(input.recurrence,20).toUpperCase()==="WEEKLY"?"WEEKLY":"NONE",active:input.active!==false,createdById:old?.createdById||user.id,createdByName:old?.createdByName||user.displayName,createdAt:old?.createdAt||t,updatedAt:t,lastReminderKey:old?.lastReminderKey||""};await put(K.plan(id),p);await activity(user,old?"PLAN_UPDATED":"PLAN_CREATED",`${title} · ${scheduledDate}`);return p}
function nextWeek(date){const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+7);return d.toISOString().slice(0,10)}
export async function completeChefPlan(user,idInput){const id=clean(idInput,120),p=await get(K.plan(id));if(!p)throw new Error("PLAN_NOT_FOUND");const t=now(),next=p.recurrence==="WEEKLY"?{...p,scheduledDate:nextWeek(p.scheduledDate),completedAt:t,completedByName:user.displayName,updatedAt:t,lastReminderKey:""}:{...p,active:false,completedAt:t,completedByName:user.displayName,updatedAt:t};await put(K.plan(id),next);await activity(user,"PLAN_COMPLETED",p.title);return next}
export async function deleteChefPlan(user,idInput){const id=clean(idInput,120),p=await get(K.plan(id));if(p){await del(K.plan(id));await activity(user,"PLAN_DELETED",p.title)}return{ok:true}}
function berlin(date=new Date()){const f=d=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Berlin",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);return{today:f(date),tomorrow:f(new Date(date.getTime()+86400000))}}
export async function runChefReminders(){const plans=await list("chef:plan:",250),{today,tomorrow}=berlin();let sent=0;for(const p of plans.filter(x=>x.active)){const kind=p.remindSameDay&&p.scheduledDate===today?"today":p.remindDayBefore&&p.scheduledDate===tomorrow?"tomorrow":"";if(!kind)continue;const key=`${p.scheduledDate}:${kind}`;if(p.lastReminderKey===key)continue;await createChefNotification({title:kind==="today"?"BB Chef · Bugünün hazırlığı":"BB Chef · Yarın hazırlanacak",body:kind==="today"?`${p.title} bugün hazırlanmalı.`:`${p.title} yarın hazırlanacak.`,url:"/chef"});await put(K.plan(p.id),{...p,lastReminderKey:key,updatedAt:now()});sent++}return{checked:plans.length,sent}}
export async function createChefNotification(input){const n={id:randomUUID(),title:clean(input.title,140),body:clean(input.body,500),url:clean(input.url||"/chef",200)||"/chef",createdAt:now()};await put(K.notification(n.id),n);await wakeChefPushSubscribers();return n}
export async function latestChefNotification(){const xs=await list("chef:notification:",20);return xs.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]||null}
export async function upsertChefPush(req,value){const sub=normalizeSchnellPushSubscription(value),cfg=getSchnellPushConfig();if(!cfg.configured)throw new Error("PUSH_NOT_CONFIGURED");if(!sub?.endpoint||!sub.keys?.p256dh||!sub.keys.auth)throw new Error("INVALID_SUBSCRIPTION");const tenantId=await getTenantId(),old=await prisma.pushSubscription.findFirst({where:{tenantId,endpoint:sub.endpoint}});if(old&&old.appScope!==CHEF_PUSH_SCOPE)throw new Error("SUBSCRIPTION_SCOPE_CONFLICT");const ua=clean(req.headers.get("user-agent"),500),data={endpoint:sub.endpoint,p256dh:sub.keys.p256dh,auth:sub.keys.auth,expirationTime:sub.expirationTime?new Date(sub.expirationTime):null,deviceTokenHash:createHash("sha256").update(sub.endpoint).digest("hex"),platform:/iphone|ipad|ipod/i.test(ua)?"ios":/android/i.test(ua)?"android":/windows/i.test(ua)?"windows":/mac/i.test(ua)?"macos":"web",userAgent:ua,locale:clean(req.headers.get("accept-language")?.split(",")[0]||"de",24)||"de",appScope:CHEF_PUSH_SCOPE,active:true,lastSeenAt:new Date(),failureCount:0};return old?prisma.pushSubscription.update({where:{id:old.id},data}):prisma.pushSubscription.create({data:{tenantId,...data}})}
export async function wakeChefPushSubscribers(){const tenantId=await getTenantId(),subs=await prisma.pushSubscription.findMany({where:{tenantId,appScope:CHEF_PUSH_SCOPE,active:true},take:20}),results=await Promise.all(subs.map(async row=>{const r=await sendEmptySchnellPush({endpoint:row.endpoint,expirationTime:row.expirationTime?new Date(row.expirationTime).getTime():null,keys:{p256dh:row.p256dh,auth:row.auth}}).catch(()=>({ok:false,expired:false})),t=new Date();await prisma.pushSubscription.update({where:{id:row.id},data:r.ok?{lastPushAt:t,lastSuccessAt:t,failureCount:0}:{active:r.expired?false:true,lastPushAt:t,lastFailureAt:t,failureCount:{increment:1}}}).catch(()=>undefined);return r.ok}));return{recipients:subs.length,ok:results.filter(Boolean).length}}
