"use client";

import ShowcaseStage from "@/components/showcase/ShowcaseStage";
import ShowcaseErrorBoundary from "@/components/showcase/ShowcaseErrorBoundary";
import { TYPE_LABELS, canonicalSceneType } from "@/lib/showcase/editor";
import type { ShowcaseDocument, ShowcasePreviewAspect, ShowcaseScene, ShowcaseSnapshot } from "@/lib/showcase/types";

type StorageState={configured:boolean;provider:"cloudinary";cloudName:string;maxUploadBytes:number};
type Props={
  screenSlug:string; scene:ShowcaseScene; sceneIndex:number; sceneCount:number; snapshot:ShowcaseSnapshot;
  previewAspect:ShowcasePreviewAspect; onPreviewAspect:(value:ShowcasePreviewAspect)=>void;
  selectedProductName?:string; selectedProductCount:number; menuPageCount:number;
  document:ShowcaseDocument; published:ShowcaseDocument; productCount:number; campaignCount:number; storage:StorageState;
  inputClass:string; onSettings:(patch:Partial<ShowcaseDocument["settings"]>)=>void;
};
function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){return <label className="block space-y-1.5"><span className="text-sm font-semibold text-stone-200">{label}</span>{children}{hint?<span className="block text-xs text-stone-500">{hint}</span>:null}</label>}
function formatBytes(value:number){const bytes=Number(value||0);if(bytes<1024)return`${bytes} B`;if(bytes<1024**2)return`${(bytes/1024).toFixed(1)} KB`;if(bytes<1024**3)return`${(bytes/1024**2).toFixed(1)} MB`;return`${(bytes/1024**3).toFixed(2)} GB`;}
export default function ShowcasePreviewSidebar(props:Props){
  const badge=props.scene.type==="product"?`${props.selectedProductCount} ürün`:props.scene.type==="menu"?`${props.menuPageCount} sayfa`:props.selectedProductName||TYPE_LABELS[canonicalSceneType(props.scene.type)];
  return <aside className="space-y-4 xl:sticky xl:top-5 xl:self-start">
    <section className="rounded-2xl border border-stone-800 bg-stone-900/55 p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-black">Canlı önizleme</h2><p className="text-xs text-stone-500">Yatay, dikey ve ultra geniş ekranı test et.</p></div><span className="rounded-full bg-stone-800 px-3 py-1 text-xs font-bold">{badge}</span></div><div className="mb-3 grid grid-cols-3 gap-1.5 rounded-xl border border-stone-800 bg-stone-950/60 p-1.5">{([['landscape','16:9 Yatay'],['portrait','9:16 Dikey'],['ultrawide','21:9 Geniş']] as Array<[ShowcasePreviewAspect,string]>).map(([value,label])=><button key={value} type="button" onClick={()=>props.onPreviewAspect(value)} className={`rounded-lg px-2 py-1.5 text-[11px] font-bold ${props.previewAspect===value?"bg-orange-500 text-black":"text-stone-400 hover:bg-stone-800"}`}>{label}</button>)}</div><ShowcaseErrorBoundary key={`${props.screenSlug}:${props.scene.id}`} label="Bu sahnenin önizlemesi oluşturulamadı"><ShowcaseStage snapshot={props.snapshot} scene={props.scene} sceneIndex={Math.max(0,props.sceneIndex)} sceneCount={props.sceneCount} preview previewAspect={props.previewAspect} online/></ShowcaseErrorBoundary></section>
    <section className="rounded-2xl border border-stone-800 bg-stone-900/55 p-4"><h2 className="font-black">Genel ekran ayarları</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Ad"><input className={props.inputClass} value={props.document.settings.name} onChange={(event)=>props.onSettings({name:event.target.value})}/></Field><Field label="Varsayılan süre"><input type="number" min={5} className={props.inputClass} value={props.document.settings.defaultDurationSeconds} onChange={(event)=>props.onSettings({defaultDurationSeconds:Number(event.target.value)})}/></Field><Field label="Canlı senkron süresi" hint="Yedek sürüm kontrolü 10–60 saniye; değişiklik yoksa tam veri indirilmez."><input type="number" min={10} max={60} className={props.inputClass} value={props.document.settings.refreshSeconds} onChange={(event)=>props.onSettings({refreshSeconds:Number(event.target.value)})}/></Field><Field label="Arka plan"><select className={props.inputClass} value={props.document.settings.background} onChange={(event)=>props.onSettings({background:event.target.value as ShowcaseDocument["settings"]["background"]})}><option value="theme">Aktif web sitesi teması</option><option value="dark">Koyu</option><option value="black">Siyah</option></select></Field><div className="sm:col-span-2"><Field label="Varsayılan QR hedefi"><input className={props.inputClass} value={props.document.settings.qrUrl} onChange={(event)=>props.onSettings({qrUrl:event.target.value})}/></Field></div><Field label="Yeni sahneler için QR açıklaması" hint="Boş bırakırsan QR kodunun altında açıklama gösterilmez."><input className={props.inputClass} value={props.document.settings.qrLabel} onChange={(event)=>props.onSettings({qrLabel:event.target.value})}/></Field><div className="sm:col-span-2"><Field label="Kayan yazı" hint="Boş bırakırsan kayan yazı tamamen gizlenir."><input className={props.inputClass} value={props.document.settings.ticker} onChange={(event)=>props.onSettings({ticker:event.target.value})}/></Field></div></div><div className="mt-4 grid gap-2 rounded-xl border border-stone-800 bg-stone-950/60 p-3 sm:grid-cols-3"><label className="flex items-center justify-between gap-2 text-sm">Saati göster<input type="checkbox" checked={props.document.settings.showClock} onChange={(event)=>props.onSettings({showClock:event.target.checked})}/></label><label className="flex items-center justify-between gap-2 text-sm">İlerleme<input type="checkbox" checked={props.document.settings.showProgress} onChange={(event)=>props.onSettings({showProgress:event.target.checked})}/></label><label className="flex items-center justify-between gap-2 text-sm">Bağlantı<input type="checkbox" checked={props.document.settings.showConnectionState} onChange={(event)=>props.onSettings({showConnectionState:event.target.checked})}/></label></div></section>
    <section className="rounded-2xl border border-stone-800 bg-stone-900/55 p-4 text-sm"><h2 className="font-black">Sistem durumu</h2><dl className="mt-3 grid grid-cols-[auto_1fr] gap-x-4 gap-y-2 text-xs"><dt className="text-stone-500">Yayın tarihi</dt><dd className="text-right font-semibold">{props.published.publishedAt?new Date(props.published.publishedAt).toLocaleString("de-DE"):"Henüz yayınlanmadı"}</dd><dt className="text-stone-500">Sürüm</dt><dd className="truncate text-right font-mono text-stone-300">{props.published.version}</dd><dt className="text-stone-500">Ürünler</dt><dd className="text-right font-semibold">{props.productCount}</dd><dt className="text-stone-500">Kampanyalar</dt><dd className="text-right font-semibold">{props.campaignCount}</dd><dt className="text-stone-500">Medya</dt><dd className={`text-right font-semibold ${props.storage.configured?"text-emerald-400":"text-amber-400"}`}>{props.storage.configured?`Cloudinary · ${props.storage.cloudName}`:"Ayarlanmadı"}</dd>{props.storage.maxUploadBytes?<><dt className="text-stone-500">En büyük dosya</dt><dd className="text-right font-semibold">{formatBytes(props.storage.maxUploadBytes)}</dd></>:null}</dl></section>
  </aside>;
}
